from pathlib import Path

import pytest
from code_genome_api.models import AuditEvent, GeneratedDocRewrite
from code_genome_api.services.doc_rewrite import (
    check_rewrite,
    citations,
    source_hash,
    split_header,
)
from fastapi.testclient import TestClient
from sqlalchemy import select
from sqlalchemy.orm import Session, sessionmaker
from test_conversations_voice import configured_settings
from test_project_knowledge import HEADERS, analysed  # noqa: F401

SOURCE = """# Risk report

> Generated by CODE GENOME (generated-docs@1) at 2026-10-06T00:00:00+00:00.

## Hotspots

- `src/a.ts` changed in 9 commits (evidence:ev_one). Fixed in commit:abc123.

## Limits

Risk is inferred (hotspot:src/a.ts).
"""


def test_check_accepts_rewrites_that_keep_every_citation() -> None:
    header, body = split_header(SOURCE)
    assert header.endswith("2026-10-06T00:00:00+00:00.")
    assert citations(body) == {"evidence:ev_one", "commit:abc123", "hotspot:src/a.ts"}
    rewritten = (
        "## Hotspots\n\nThe file `src/a.ts` is busy: 9 commits (evidence:ev_one), one of them a "
        "fix (commit:abc123).\n\n## Limits\n\nThis is an inferred estimate (hotspot:src/a.ts).\n"
    )
    assert check_rewrite(body, rewritten).accepted


def test_check_rejects_dropped_or_invented_citations_and_lost_headings() -> None:
    _, body = split_header(SOURCE)
    dropped = check_rewrite(body, body.replace(" Fixed in commit:abc123.", ""))
    assert not dropped.accepted and "dropped 1 citation" in (dropped.reason or "")
    invented = check_rewrite(body, body + "\nAlso see evidence:ev_fake.\n")
    assert not invented.accepted and "evidence:ev_fake" in (invented.reason or "")
    no_heading = check_rewrite(body, body.replace("## Limits", "### Limits"))
    assert not no_heading.accepted and "heading" in (no_heading.reason or "")


def test_source_hash_ignores_the_generation_timestamp() -> None:
    later = SOURCE.replace("2026-10-06T00:00:00", "2026-10-07T12:00:00")
    assert source_hash(SOURCE) == source_hash(later)
    assert source_hash(SOURCE) != source_hash(SOURCE.replace("9 commits", "8 commits"))


def test_rewrite_requires_a_configured_model(
    analysed: Path,  # noqa: F811
    client: TestClient,
) -> None:
    response = client.post("/api/v1/repositories/repo_structural/docs/rewrite", headers=HEADERS)
    assert response.status_code == 409
    assert response.json()["code"] == "GEMINI_NOT_CONFIGURED"
    docs = client.get("/api/v1/repositories/repo_structural/docs", headers=HEADERS).json()
    assert docs["rewrite_available"] is False
    assert all(item["rewritten_markdown"] is None for item in docs["documents"])


def test_rewrites_are_kept_only_when_citations_survive(
    analysed: Path,  # noqa: F811
    client: TestClient,
    session_factory: sessionmaker[Session],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr("code_genome_api.routes.insights.get_settings", configured_settings)
    calls: list[str] = []
    rejected_once: list[str] = []

    def fake_rewrite(*, api_key: str, model: str, markdown: str, timeout_seconds: float) -> str:
        calls.append(markdown)
        if "evidence:" in markdown and not rejected_once:
            # Drop every citation from one document: that rewrite must be rejected.
            rejected_once.append(markdown)
            return citations_removed(markdown)
        return "Readable version.\n\n" + markdown

    monkeypatch.setattr("code_genome_api.routes.insights.rewrite_document_markdown", fake_rewrite)
    url = "/api/v1/repositories/repo_structural/docs"
    response = client.post(f"{url}/rewrite", headers=HEADERS)
    assert response.status_code == 200, response.text
    documents = {item["name"]: item for item in response.json()["documents"]}
    accepted = [item for item in documents.values() if item["rewrite"]["status"] == "accepted"]
    assert accepted
    for item in accepted:
        assert "Readable version." in item["rewritten_markdown"]
        # The deterministic provenance header is kept verbatim.
        assert item["rewritten_markdown"].startswith(item["markdown"].split("\n\n", 1)[0])
    rejected = [item for item in documents.values() if item["rewrite"]["status"] == "rejected"]
    assert len(rejected) == 1
    for item in rejected:
        assert item["rewritten_markdown"] is None
        assert item["rewrite"]["reason"]

    # A second request reuses stored rewrites for unchanged documents.
    first_calls = len(calls)
    client.post(f"{url}/rewrite", headers=HEADERS)
    assert len(calls) == first_calls
    shown = client.get(url, headers=HEADERS).json()
    assert {item["name"] for item in shown["documents"] if item["rewritten_markdown"]} == {
        item["name"] for item in accepted
    }
    with session_factory() as db:
        rows = list(db.scalars(select(GeneratedDocRewrite)))
        assert rows and all(row.workspace_id == "ws_structural" for row in rows)
        assert db.scalar(select(AuditEvent).where(AuditEvent.action == "repository.docs.rewritten"))
    other = client.get(url, headers={"X-Workspace-ID": "ws_other", "X-User-ID": "usr_other"})
    assert other.status_code in {403, 404}


def citations_removed(markdown: str) -> str:
    import re

    return re.sub(r"\(?\b(?:evidence|commit|hotspot|module|change):[\w.\-/@]+\)?", "", markdown)
