"""Optional model-written versions of the generated documents (``docs-rewrite@1``).

The deterministic document is the source of truth. A rewrite is accepted only when it keeps
every ``## `` heading and every citation of the source and cites nothing the source does not;
otherwise the deterministic text is served and the rejection reason is stored.
"""

import hashlib
import re
from dataclasses import dataclass

REWRITE_VERSION = "docs-rewrite@1"
MAX_SOURCE_CHARS = 40_000
_CITATION = re.compile(r"\b(?:evidence|commit|hotspot|module|change):[A-Za-z0-9_][\w.\-/@]*")
_GENERATED_LINE = re.compile(r"^> Generated by .*$", re.MULTILINE)


@dataclass(frozen=True)
class RewriteCheck:
    accepted: bool
    reason: str | None


def citations(markdown: str) -> set[str]:
    return {match.group(0).rstrip(".-/") for match in _CITATION.finditer(markdown)}


def headings(markdown: str) -> list[str]:
    return [line.strip() for line in markdown.splitlines() if line.startswith("## ")]


def split_header(markdown: str) -> tuple[str, str]:
    """(fixed header: title and provenance note, body the model may rewrite)."""
    match = _GENERATED_LINE.search(markdown)
    if match is None:
        return "", markdown
    return markdown[: match.end()], markdown[match.end() :]


def source_hash(markdown: str) -> str:
    """Hash of the document without its generation timestamp line, which changes per request."""
    return hashlib.sha256(_GENERATED_LINE.sub("", markdown).encode()).hexdigest()


def check_rewrite(source_body: str, rewritten: str) -> RewriteCheck:
    expected, produced = citations(source_body), citations(rewritten)
    missing = sorted(expected - produced)
    invented = sorted(produced - expected)
    lost_headings = [item for item in headings(source_body) if item not in headings(rewritten)]
    problems: list[str] = []
    if missing:
        problems.append(f"dropped {len(missing)} citation(s), e.g. {missing[0]}")
    if invented:
        problems.append(
            f"cited {len(invented)} reference(s) not in the evidence, e.g. {invented[0]}"
        )
    if lost_headings:
        problems.append(f"lost {len(lost_headings)} heading(s), e.g. {lost_headings[0]}")
    if problems:
        return RewriteCheck(False, "; ".join(problems))
    return RewriteCheck(True, None)
