import logging

from fastapi import APIRouter, Request, status

from ..audit import record_audit_event
from ..auth import Actor, Database
from ..config import get_settings
from ..errors import AppError
from ..ids import new_id
from ..schemas import VoiceSessionCreate, VoiceSessionResponse
from ..services.gemini import GeminiProviderError
from ..services.gemini_live import CONSTRAINED_WEBSOCKET_URL, create_live_session
from .intelligence import _repository, _snapshot

router = APIRouter(tags=["voice"])
logger = logging.getLogger(__name__)


@router.post(
    "/voice/sessions", response_model=VoiceSessionResponse, status_code=status.HTTP_201_CREATED
)
def create_voice_session(
    payload: VoiceSessionCreate, request: Request, db: Database, actor: Actor
) -> VoiceSessionResponse:
    repository = _repository(db, payload.repository_id, actor)
    snapshot = _snapshot(db, payload.repository_id, actor)
    settings = get_settings()
    api_key = settings.gemini_api_key
    if api_key is None or not api_key.get_secret_value():
        raise AppError(
            503,
            "VOICE_UNAVAILABLE",
            "Voice agent unavailable",
            "Set GEMINI_API_KEY on the API server to enable the voice agent.",
        )
    try:
        session = create_live_session(
            api_key=api_key.get_secret_value(),
            model=settings.gemini_live_model,
            voice=payload.voice,
            language=payload.language,
            repository_name=repository.external_id,
            snapshot_sha=snapshot.commit_sha,
            timeout_seconds=settings.gemini_timeout_seconds,
            ttl_minutes=settings.gemini_live_session_minutes,
        )
    except GeminiProviderError as error:
        logger.warning(
            "gemini_live_token_failed",
            extra={"repository_id": repository.id, "reason": str(error)},
        )
        raise AppError(
            502,
            "VOICE_PROVIDER_ERROR",
            "Voice agent unavailable",
            "The voice provider did not issue a session. Try again shortly.",
        ) from error
    session_id = new_id("vcs")
    record_audit_event(
        db,
        workspace_id=actor.workspace_id,
        actor_id=actor.user_id,
        action="voice_session.created",
        resource_type="repository",
        resource_id=repository.id,
        request_id=request.state.request_id,
        after_hash=session_id,
    )
    db.commit()
    return VoiceSessionResponse(
        id=session_id,
        repository_id=repository.id,
        snapshot_sha=snapshot.commit_sha,
        model=settings.gemini_live_model,
        voice=payload.voice,
        language=payload.language,
        websocket_url=CONSTRAINED_WEBSOCKET_URL,
        token=session.token,
        expires_at=session.expires_at,
        new_session_expires_at=session.new_session_expires_at,
        setup=session.setup,
        limitations=[
            "Spoken answers are generated by Gemini Live from evidence returned by the "
            "repository search tool; inspect the cited evidence on screen.",
            "Speech recognition can mishear names and paths; transcripts are best-effort.",
        ],
    )
